services:
  service:
    build: .
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8000/health || exit 1
      interval: 1m
      retries: 3
      timeout: 10s
      start_period: 1m
    ports:
      - 127.0.0.1:8000:8000
