site_name: deadnews-template-python
repo_url: https://github.com/deadnews/deadnews-template-python
edit_uri: blob/main/docs/

nav:
  - Overview: index.md
  - Changelog: changelog.md
  - API reference: reference/ # defer to gen-files + literate-nav
  - OpenAPI: openapi.md # defer to gen-files

watch:
  - src
  - README.md
  - CHANGELOG.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        name: Switch to light mode
        icon: material/brightness-auto
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        name: Switch to dark mode
        icon: material/brightness-7
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        name: Switch to system preference
        icon: material/brightness-4
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

markdown_extensions:
  - attr_list
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
  - swagger-ui-tag
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_nav.py
        - docs/scripts/gen_openapi.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            docstring_style: google
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            members_order: source
            merge_init_into_class: true
            separate_signature: true
            show_root_full_path: false
            show_root_heading: true
            show_signature_annotations: true
            show_submodules: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
          import:
            - https://docs.python.org/3/objects.inv
