[tool.poetry]
name = "deadnews-python-template"
version = "placeholder"
description = "Python Project Template"
authors = ["DeadNews <aurczpbgr@mozmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/DeadNews/deadnews-python-template"
repository = "https://github.com/DeadNews/deadnews-python-template"
keywords = ["python", "template", "layout"]
classifiers = ["Operating System :: OS Independent"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.ci.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
mypy = "^1.2.0"
poethepoet = "^0.19.0"
ruff = "^0.0.263"
safety = "^2.3.5"

[tool.poetry.group.test.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"

[tool.poetry.group.build.dependencies]
poetry-dynamic-versioning = "^0.21.4"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.black]
line-length = 99

[tool.isort]
line_length = 99
profile = "black"

[tool.mypy]
disallow_untyped_defs = true
follow_imports = "silent"
ignore_missing_imports = true
show_column_numbers = true
show_error_codes = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["tests.*"]
allow_untyped_defs = true

[tool.pytest.ini_options]
addopts = "--verbose --cov=./src"
testpaths = ["tests"]
markers = ["docker", "slow"]

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]

[tool.poe.tasks]
isort = "isort . --check-only --diff"
black = "black . --check --diff"
mypy = "mypy ."
ruff = "ruff check ."
safety = "safety check -r pyproject.toml -o bare"
ci.sequence = ["isort", "black", "mypy", "ruff"]  # safety

[tool.ruff]
line-length = 99
select = [
  "A",   # flake8-builtins
  "ARG", # flake8-unused-arguments
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "C90", # mccabe
  "E",   # pycodestyle
  "F",   # pyflakes
  # "I",   # isort
  "ISC", # flake8-implicit-str-concat
  "N",   # pep8-naming
  "PIE", # flake8-pie
  "PT",  # flake8-pytest-style
  "PTH", # flake8-use-pathlib
  "RUF", # ruff-specific rules
  "S",   # flake8-bandit
  "SIM", # flake8-simplify
  "T10", # flake8-debugger
  "UP",  # pyupgrade
]
ignore = [
  "E501", # Line too long
  "S603", # Calling subprocess.Popen with shell=False
]

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = false

[tool.ruff.per-file-ignores]
"tests/*" = ["S"]
