[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry]
name = "deadnews-template-python"
version = "0.0.0"
description = "Python Project Template"
authors = ["DeadNews <aurczpbgr@mozmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/DeadNews/deadnews-template-python"
repository = "https://github.com/DeadNews/deadnews-template-python"
keywords = ["python", "template", "layout"]
classifiers = ["Operating System :: OS Independent"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.ci.dependencies]
black = "^23.3.0"
mypy = "^1.2.0"
poethepoet = "^0.19.0"
ruff = "^0.0.263"

[tool.poetry.group.test.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"

[tool.poe.tasks]
ruff = "ruff check . --diff"
black = "black . --check --diff"
mypy = "mypy ."
ci.sequence = ["ruff", "black", "mypy"]

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.black]
line-length = 99

[tool.isort]
line_length = 99
profile = "black"

[tool.mypy]
disallow_untyped_defs = true
follow_imports = "silent"
ignore_missing_imports = true
show_column_numbers = true
show_error_codes = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["tests.*"]
allow_untyped_defs = true

[tool.pytest.ini_options]
addopts = "--verbose --cov=./src"
testpaths = ["tests"]
markers = ["docker", "slow"]

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]

[tool.ruff]
line-length = 99
select = [
  "A",   # flake8-builtins
  "ARG", # flake8-unused-arguments
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "C90", # mccabe
  "E",   # pycodestyle
  "ERA", # eradicate
  "F",   # pyflakes
  "I",   # isort
  "INP", # flake8-no-pep420
  "ISC", # flake8-implicit-str-concat
  "N",   # pep8-naming
  "PIE", # flake8-pie
  "PL",  # pylint
  "PT",  # flake8-pytest-style
  "PTH", # flake8-use-pathlib
  "RSE", # flake8-raise
  "RUF", # ruff-specific rules
  "S",   # flake8-bandit
  "SIM", # flake8-simplify
  "SLF", # flake8-self
  "T10", # flake8-debugger
  "T20", # flake8-print
  "TCH", # flake8-type-checking
  "TID", # flake8-tidy-imports
  "UP",  # pyupgrade
]
ignore = [
  "E501",    # Line too long
  "PLR2004", # Magic value used in comparison
  "S113",    # Missing requests timeout
  "S603",    # Calling subprocess.Popen with shell=False
]

[tool.ruff.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = false

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["S"]
