name: Check code quality

on:
  workflow_call:
    inputs:
      setup-vapoursynth:
        default: false
        type: boolean

jobs:
  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup vapoursynth
        if: ${{ inputs.setup-vapoursynth }}
        uses: deadnews/setup-vapoursynth@main

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Check code quality
        run: poetry run poe ci
