name: Deps Review

on:
  pull_request:

permissions:
  contents: read

jobs:
  deps-review:
    name: Deps Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Dependency Review
        uses: actions/dependency-review-action@1360a344ccb0ab6e9475edef90ad2f46bf8003b1 # v3
