name: Docker

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  id-token: write
  packages: write
  security-events: write

jobs:
  docker:
    name: Docker
    uses: deadnews/deadnews-template-docker/.github/workflows/docker-reusable.yml@latest

  docker-pypy:
    name: Docker PyPy
    uses: deadnews/deadnews-template-docker/.github/workflows/docker-reusable.yml@latest
    with:
      build-args: BASE_IMAGE=pypy:3.10-slim@sha256:41f5d56ab6ebb483a73c047622e98f511173f209ad05358cd1da0d3b40874ec9
      flavor: |
        suffix=-pypy
