name: Docker

on:
  push:
    branches: [main]
    tags: [v*.*.*]
  pull_request:
    paths: [Dockerfile*]

permissions:
  contents: read
  id-token: write
  packages: write
  security-events: write

jobs:
  docker:
    name: Docker
    uses: deadnews/deadnews-template-docker/.github/workflows/docker-reusable.yml@main
